### PR TITLE
Add missing Test::Requires dep

### PR DESCRIPTION
**Pull request by toddr**

### CODE REVIEW

**Comment by karenetheridge** [comment]
Test::Requires should be declared as a 'test' prereq, not 'build'. See https://metacpan.org/pod/CPAN::Meta::Spec#Phases

**Comment by toddr** [comment]
@karenetheridge I'm just stabbing here. I have 0 experience with MBT. What patch do you suggest?

**Comment by karenetheridge** [comment]
As I said, declare Test::Requires as a 'test' prereq not 'build'.  But I don't see how Test::Requires is needed at all, since 'CGI' is already listed as a prereq. Those calls in the tests can just be removed.

Also ExtUtils::MakeMaker shouldn't be listed as a prereq at all, but this is mostly harmless as it's in core.

**Comment by gfx** [comment]
There was only "build" prerequisites when the library was developed.

Will change the before release. Thanks.

**Pull request merged**
